### ISSUE TITLE
Integrate clinvar curator functionality into genegraph admin UI 

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#27]
Add react.js framework to the admin app.

Acceptance:
Spend no more than 2 days to see if we can get the SCV data table working (focus on how we deal with managing state via javascript/clojurescript). - try to keep the app state in the atom otherwise it may not be in line with Tristan's vision.

Kyle intends to find libs to use some complex components (grids) and try them out in dev to learn the pros and cons.
Based on that Kyle will report back and we will determine if it is worthwhile to go forward with React.

**Comment by theferrit32** [comment]
The purpose of this ticket is to make the clinvar variant assertion search and results table look better and easier to use from a UI standpoint by leaning on some frontend styling frameworks.
