### ISSUE TITLE
Document v1 MVP developer rules for binning, excluding and aggregating curated SCVs

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#31]
Use data in worksheet ClinGenVar Stakeholder Discussion Worksheet  to go through the process of manually creating a display mock up with this data, with specifications for each step of the process.

Review and get sign off from Heidi with the presumption it will be our first pilot of the post-curated SCVs.

This document is intended for generating development tasks with clear and comprehensive rules.

NOTE: Heidi will work on a user facing policy document that describes the data processing of Clinvar (the how and the why behind our rules).

Server-side rules encompass the process for how SCV records are binned for ClinGen Representing ClinVar and how ClinGenVar rules are used to bin and exclude records. 

Acceptance criteria:
A document by the development team describing the infrastructure for 1) how rules are to be specified to the system for execution, 2) the mechanism that determines how and when rules are to be executed by the system, 3) details for how rule execution errors are handled and rectified, and 4) how to determine and track the results of rule execution are on the current data set.

Here are examples of each of the above points from a non-technical user’s perspective: 

How will this system be set up to enable changes to the way SCVs are aggregated without hardcoding it?

What happens when there are errors during rule execution? Does all rule processing just stop? Or do other rules get executed after an error? What notification happens on error? How are rules corrected and resubmitted to the system for future execution?

How do I know that the rules have executed successfully for a set of data? How do I know for a given SCV for example, which rules were applied that impacted the original SCV in some way?

**Comment by dazzariti** [comment]
Current document outlining ClinVar static binning rules project rules https://docs.google.com/document/d/1Npxnwi2J85qE9nMry8jdeOV1H-wVMLHaMc12HUdXN78/edit?usp=sharing, next version will include versioning

**Comment by dazzariti** [comment]
Need to review with Heidi what the cutoff is for what begins being coded
