### ISSUE TITLE
Load full ClinVar dataset based on Phase2a requirements

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#32]
Acceptance Criteria:
An API user can perform a GraphQL query for SCV data:

**SCV Field List**
- SCV ID
- Last Evaluated Date
- Interpretation (clinsig, classification) - per ClinVar
- Review Status
- Collection Method*
- Submitter (Name, Org ID, Abbreviation)
- Allele Origin*
- Date submitted
- Star level/review status
- Most current ClinVar release date

*Need to unpack these fields - defer to separate ticket if needed

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
