### ISSUE TITLE
Re-organize projects within Curator product for better zenhub utility

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#33]
Zenhub has the concept of projects (which may be linked to github) and milestones and epics.

Consider how our "Phase 2a, 2b, etc" approach at the beginning might be applied (or refined) to leverage shorter length and super focused deliverables.

Phases defined here: https://lucid.app/lucidchart/invitations/accept/78db27f7-699a-4bc3-b116-9700aa3f15e6

Phase 2a: Provide a UI display of any ClinVar data binned into the defined "classification context" bins AND finalize requirements for exclusion rules and binning going forward

Acceptance Criteria:
Agreed up on scope statement for Phase 2a MVP and associated set of user stories.

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
