### ISSUE TITLE
Add remaining elements to Dosage Jira data to Genegraph

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#44]
This request was made at the 8/31/21 meeting in Bethesda. It is aimed at removing the need for the website team to do an end-run around genegraph to get the missing data from Dosage (Jira) in order to display and search the dosage curation completely.

Phil has done the requirements gathering to identify the elements that are missing.  They can be found [here](https://broadinstitute.atlassian.net/browse/CGWM-339)

**Comment by KelseaChang5** [comment]
**Website Request Checklist:**
- [ ] Estimated time based on quick review:
- [ ] Estimated priority level:
- [ ] Questions for Phil during next meeting:

**Comment by tnavatar** [comment]
Am closing this ticket; is vague and large in scope. We will be reviewing the data available that will be carried over with Erin; this will serve as the specification for following work.
