### ISSUE TITLE
Obtain VRS representation of variant data from MetaKB variant normalization service

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/curator#46]
The Clinvar VCV streaming work being done for Kevin R. at Baylor needs to include the GA4GH Variant Representation Specification (VRS) representation of the variant in the stream. This representation will be obtained from the MetaKB variant normalization service. 

https://normalize.cancervariants.org/variation

https://docs.google.com/presentation/d/1TqiQ_ZeU1a92aFswa0OM3Q62kxzN4Hrk1U3FRBFHm_k/edit?usp=sharing

https://docs.google.com/presentation/d/1TqiQ_ZeU1a92aFswa0OM3Q62kxzN4Hrk1U3FRBFHm_k/edit?usp=sharing

https://github.com/cancervariants

The service currently doesn't handle all representations. And at a minimum it will need to handle a default fallback text representation.

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: @larrybabb  to rework ticket
