### ISSUE TITLE
Add Follow Up actions to VCEP Work Queue Curation reports.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#52]
For the existing VCEP queue sheets found in the [ClinVar Curation Project VCEP queues](https://drive.google.com/drive/folders/1KOWUv_J8RYvzZnu8chBzuKd2JExy3Vu0) shared folder make sure the Follow Up annotations are showing. 

DoD: For each VCEP queue file. Modify the Dashboard's Curation count graph to show the number of curations per action type. On the Queue and SCV Data tab, make sure Follow Up annotated SCVs show in a yellow background.

**Comment by larrybabb** [comment]
@KelseaChang5 can you verify the DoD on this and close if okay?

**Comment by KelseaChang5** [comment]
Confirmed "Follow Up" SCVs show up as yellow in the Queue and SCV Data tabs. Closing ticket
