### ISSUE TITLE
Send a copy of the ClinVar Curation Submission spec to Tristan

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#69]
Tristan needs the clinvar submission spec to begin  submitting CNV curations.

**Comment by larrybabb** [comment]
@tnavatar Here is an excerpt from the first two records in the last submission batch file I sent to ClinVar.

```json
[{
  "Variation ID": "978973",
  "VCV": "VCV000978973",
  "SCV ID": "SCV004805987.1",
  "Submitter ID": "500184",
  "Action": "flagging candidate",
  "Reason": "Outlier claim with insufficient supporting evidence",
  "Notes": null,
  "Timestamp": "2024-10-03T14:35:09Z",
  "Date Created": "2024-10-27",
  "ClinVar Release Date": "2024-10-27",
  "Is Annotation Outdated": "false",
  "Is Annotated SCV Deleted": "false",
  "SCV Deleted Release Date": null
}, {
  "Variation ID": "38612",
  "VCV": "VCV000038612",
  "SCV ID": "SCV001428939.1",
  "Submitter ID": "506086",
  "Action": "flagging candidate",
  "Reason": "Outlier claim with insufficient supporting evidence",
  "Notes": null,
  "Timestamp": "2024-10-04T14:03:02Z",
  "Date Created": "2024-10-27",
  "ClinVar Release Date": "2024-10-27",
  "Is Annotation Outdated": "false",
  "Is Annotated SCV Deleted": "false",
  "SCV Deleted Release Date": null
}]
```

The fields are defined as follows:
* Variation ID : The clinvar variation id as a string (e.g. "207018")
* VCV : The VCV accession without version as a string (e.g. "VCV000207018")
* SCV ID : The SCV accession WITH version as a string (e.g. "SCV000242802.10")
* Submitter ID : The clinvar submitter id (aka org id) as a string (e.g. "26957")
* Action : The action. Always "flagging candidate"
* Reason  : The reason for flagging candidate action. (e.g. "Older claim that does not account for recent evidence")
* Notes   : Any additional notes that the curator wants to share publicly about the curation
* Timestamp : The ISO formatted timestamp that the annotation was made by the curator. (e.g. "2024-10-09T17:10:09Z")
* Date Created  : The yyyy-mm-dd formatted date the batch file was created. (e.g. "2024-10-28") should be same for all records in a single batch.
* ClinVar Release Date  : The yyyy-mm-dd formatted date against which clinvar release file the curations were based (e.g. "2024-10-27")
* Is Annotation Outdated  :  An optional boolean flag indicating whether the specific submission is older than the version in the file (e.g. "false"). NOTE: this is a silly and useless field but it made it in to the file format so...?
* Is Annotated SCV Deleted  : An optional boolean flag indicating whether the SCV being submitted is deleted in the clinvar release it was made against (e.g. "false") NOTE: another useless field I added for testing and never removed.
* SCV Deleted Release Date : An optional yyyy-mm-dd formatted field for the date of the clinvar release that the SCV being flagged was deleted in. (e.g.  null) NOTE: another test field that made it in.

**Comment by tnavatar** [comment]
Thanks Larry!
